version: '3'
services:
  web:
    build:
      context: .
      args:
        https_enabled: false
    volumes:
      - ./generated-files/public-html:/usr/local/apache2/htdocs/
    ports:
      - "127.0.0.1:4433:443"
