- hosts: app
  name: Generate public-html files
  vars:
    folders:
      - 'generated-files'                    #0
      - 'generated-files/markdown-html'      #1
      - 'generated-files/public-html'        #2
      - 'generated-files/public-html/images' #3
  tasks:
    - name: Create directories
      delegate_to: localhost
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ folders }}"

    - name: Convert all Markdown to HTML
      delegate_to: localhost
      shell: "cd artifacts; perl markdown.pl --html4tags {{ item }} > ../{{ folders[1] }}/{{ item | basename }}.html"
      register: shell_output
      with_fileglob:
        - "templates/markdown/*.md"

    - name: Template out public-html/ from previously generated HTML
      delegate_to: localhost
      template:
        src: "templates/site.html.j2"
        dest: "{{ folders[2] }}/{{ (item.path | basename).split('.') | first }}.html"
      with_filetree: "{{ folders[1] }}"
      when: item.state == 'file'

    - name: Copy images to public-html
      delegate_to: localhost
      copy:
        src: "{{ item }}"
        dest: "{{ folders[3] }}/{{ item | basename }}"
      with_fileglob:
        - "templates/images/*"
